f = open("abc.txt","w")
f.write('sampath kumar\n')
print("File Name: ",f.name)
print("File Mode: ",f.mode)
print("Is File Readable: ",f.readable())
print("Is File Writable: ",f.writable())
print("Is File Closed : ",f.closed)
f.write("Durga\n")
f.write("Software\n")
f.write("Solutions\n")
print("Data written to the file successfully")
f.close()
f = open("abc.txt","r")
data = f.read()
print(data)
f.close()
lst=["sunny\n","bunny\n","vinny\n","chinny"]
f = open("abc.txt","w")
f.writelines(lst)
f.close()

f = open("abc.txt","r")
data = f.read()
print(type(data))
print(data)
for i in data:
    print(i)
f.close()

